### ISSUE TITLE
ERROR: Unexpected token ] in JSON at position 41

### ISSUE THREAD

**Issue by buahaga** [maciejtreder/ng-toolkit#312]
## I'm submitting a...

<pre><code>
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ x] @ng-toolkit/universal
</code></pre>

## Environment

<pre><code>
Angular version: 6.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10  
- Platform:  

Others:

</code></pre>

**Comment by maciejtreder** [comment]
@buahaga Could you provide more details? An issue occurs in the browser? console? server?

**Comment by buahaga** [comment]
it occures in console by npm install

**Comment by maciejtreder** [comment]
Why did you check ‚Chrome’ as a browser?
Could you provide full command output and info about your operating system + node version + angular CLI version?

**Comment by buahaga** [comment]
node 10, angular 6.0.1
and I just checked it again - and all works
so I think this issue was only my fault
thanks a lot for your work))

**Comment by maciejtreder** [comment]
You’re welcome. Feel free to star the project, support it on opencollective and share with friends! :)

**Comment by buahaga** [comment]
yep, I thin it is)
in angular 5 conf.file for universal is angular-cli.json,
in angular 6 - angular.json
i think my problem was because I mixed it up, trying to add second app like in angular 5-tutorial

**Comment by maciejtreder** [comment]
So that could be the case.. Ok. I will at the check to the schematics if customer is using latest CLI version.

Thanks.

**Comment by ribalnasr** [comment]
i checked both threads and can't see the solution. how was this fixed? cuz i'm having this same issue now with node 8.11.2 and ng 6.0.0.
help please. thank you :)

**Comment by maciejtreder** [comment]
@ribalnasr Could you provide link to your repository? Did you host it somewhere?

**Comment by ribalnasr** [comment]
it is now: https://github.com/ribalnasr/slisor
the guy in the tutorial said you were that responsive but i thought he'd be exaggerating! :)

**Comment by maciejtreder** [comment]
I am, if I am in front of comptuer or other device. I will try to check your repository soon :)

**Comment by ribalnasr** [comment]
i noticed that while this is a firebase project, i wasn't using the serverless approach, so i did, and while this worked perfectly with no error:
$ ng add @ng-toolkit/serverless --provider firebase --firebaseProject [your_project_ID],

this didn't: $ npm run build:prod:deploy

the error appear in the deploy stage when trying to upload functions. it says that there is not such file './dist/server'
when i navigate to the functions folder, the dist folder was build with all the usual ng build files, but there were no server.ts file as the error says.

**Comment by JamesDevGit** [comment]
HI @maciejtreder, first let me congratulate you on your fantastic work on the toolkit. 

I just had a similar issue running- ng add @ng-toolkit/universal 
error - Unexpected token ] in JSON at position 44

ng add @ng-toolkit/serverless --provider firebase --firebaseProject - installed without errors

build still passes but my <app-root> is still empty.

----------------
 node v8.11.1
Angular CLI: 6.0.7
Node: 8.11.1
OS: win32 x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.0.1
@angular/cli                      6.0.7
@angular/flex-layout              6.0.0-beta.15
@angular/material                 6.0.1
@angular/pwa                      0.6.8
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.8
@schematics/update                0.6.7
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

Thanks in advance

**Comment by maciejtreder** [comment]
@JamesDevGit This should be fixed in the recent release (1.1.19). The problem was trailing commas in the decorators declaration (in ppl projects). That's why `JSON.parse()` couldn't finish successfully.

**Comment by acint** [comment]
Hi @maciejtreder , i still have this issue. my release is 1.1.40. can you help?

**Comment by bikas-kumar** [comment]
Getting error while running command "ng add @ng-toolkit/serverless --provider aws"
[bugsnag] Loaded!
ERROR MESSAGE: Unexpected token / in JSON at position 0
ERROR STACKTRACE: SyntaxError: Unexpected token / in JSON at position 0
    at JSON.parse (<anonymous>)

![image](https://user-images.githubusercontent.com/40659871/87786953-7abb6480-c858-11ea-8a83-5fff2fc1f6a1.png)

**Comment by luisgcs** [comment]
> 
> 
> Getting error while running command "ng add @ng-toolkit/serverless --provider aws"
> [bugsnag] Loaded!
> ERROR MESSAGE: Unexpected token / in JSON at position 0
> ERROR STACKTRACE: SyntaxError: Unexpected token / in JSON at position 0
> at JSON.parse ()
> 
> ![image](https://user-images.githubusercontent.com/40659871/87786953-7abb6480-c858-11ea-8a83-5fff2fc1f6a1.png)

I have the same error. You can solve this?

**Comment by bikas-kumar** [comment]
@luisgcs What is your Angular cli version?
Your angular cli version must be 8 or below

**Comment by praveenraghuvanshi** [comment]
I am still getting error with Angular CLI version < 8. Can someone help?

**Comment by bikas-kumar** [comment]
@praveenraghuvanshi share error message with command
