### ISSUE TITLE
npm run build:prod is showing the type error TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by BattiniSantthosh** [maciejtreder/ng-toolkit#457]
I have added the angular universal form this "ng add @ng-toolkit/universal" code.

Next "npm run build:prod" typing this cmd then showing the below error.

TypeError: Cannot read property 'properties' of undefined
    at module.exports (D:\Angular\awesome-seo\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at D:\Angular\awesome-seo\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (D:\Angular\awesome-seo\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Comment by yaashaswi** [comment]
"webpack": "^4.20.2",
    "webpack-cli": "^3.1.1",
    "webpack-dev-server": "^3.1.9",

Install this. I've solved by this.

**Comment by HARIPRASADHARI** [comment]
@yaashaswi
Working fine Thanks,

**Comment by pabloservin** [comment]
i'm having the same issue :(

I installed what @yaashaswi said but still doesn't work

**Comment by pabloservin** [comment]
this works! but have to be the exact versions @yaashaswi commented.
