### ISSUE TITLE
error when trying to install @ngtoolkit/serverless

### ISSUE THREAD

**Issue by m47een** [maciejtreder/ng-toolkit#511]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[X] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
When trying to install @ng-toolkit/serverkess it throws an error

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! serverless@1.26.1 postinstall: `node ./scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the serverless@1.26.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

## Minimal reproduction of the problem with instructions
run 
   ng add @ng-toolkit/serverless

**Comment by saprative** [comment]
facing the same bug

**Comment by kavin404** [comment]
Does anyone know how to fix it?

**Comment by AbuHani** [comment]
Open 
`%userprofile%\.serverlessrc` in editor and 
set `trackingDisabled` to `true`

**Comment by T04435** [comment]
I have solved this issue by updating node

Error on 10.10 Solved in 11.10.1

**Comment by Unny** [comment]
I am still getting the same error while using Node version 10.15.3, serverless ver 1.38.0, but in package.json file the version is shown as 1.26.1. Please help to solve the issue

**Comment by AbuHani** [comment]
@Unn

> I am still getting the same error while using Node version 10.15.3, serverless ver 1.38.0, but in package.json file the version is shown as 1.26.1. Please help to solve the issue

did you try my solution ?

**Comment by Unny** [comment]
Thanks Abu Hani for the quick reply. Could you please know how to open serverlessrc using an editor. I'm using Visual Studio Code.

**Comment by AbuHani** [comment]
@Unny open CMD and run `"%userprofile%\.serverlessrc"` with double quotation marks

and set trackingDisabled to true

**Comment by Unny** [comment]
Great AbuHani..it worked. Thanks a lot. Now let me try npm run build:serverless:deploy

**Comment by Unny** [comment]
npm run build:serverless:deploy failed, with error, AbuHani any idea?

![image](https://user-images.githubusercontent.com/24270143/54216748-41f6d700-4510-11e9-99a2-6d66437743e9.png)

**Comment by Unny** [comment]
Solved. Updated webpack-cli to 3.1.1 and it ran

**Comment by AbuHani** [comment]
@Unny Happy to hear that. Good luck!

**Comment by KingDarBoja** [comment]
Closed for housekeeping purposes.
